
slices:
  - sources:
      - model: huihui-ai/Qwen2.5-Coder-7B-Instruct-abliterated
        layer_range: [0, 28]
      - model: netcat420/qwen2.5-MFANN-7b-v1.1
        layer_range: [0, 28]
merge_method: slerp
base_model: huihui-ai/Qwen2.5-Coder-7B-Instruct-abliterated
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5 # fallback for rest of tensors
dtype: float16
